Algoritmo "atv_04"

Var
distancia_percorrida, combustivel_gasto, consumo_medio: real

Inicio
escreval("Digite a distância total percorrida pelo automóvel (em km):")
leia(distancia_percorrida)

escreval("Digite o total de combustível gasto (em litros):")
leia(combustivel_gasto)

consumo_medio <- distancia_percorrida / combustivel_gasto

escreval("O consumo médio do automóvel é: ", consumo_medio, " km\l")




Fimalgoritmo